accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('register/', views.registerPage,name='register'),
    path('login/', views.loginPage,name='login'),
    path('logout/', views.logoutUser, name="logout"),

    path('', views.home, name='home'),
    path('user/',views.userPage,name='user_page'),
    path('account/',views.accountSettings,name='account'),
    path('products/', views.products,name='products'),
    path('customer/<str:pk_test>/', views.customer,name='customer'),

    path('create_order/<str:pk>/', views.createOrder,name='create_order'),
    path('update_order/<str:pk>/', views.updateOrder,name='update_order'),
    path('delete_order/<str:pk>/', views.deleteOrder,name='delete_order'),

]

crm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from accounts import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
    user=models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)#when user deleted relationship delete
    name=models.CharField(max_length=200)
    phone=models.CharField(max_length=200)
    profile_pic=models.ImageField(default="rezowan.jpg",null=True,blank=True)
    email=models.CharField(max_length=200,null=True)
    date_created=models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Product(models.Model):
    CATEGORY=(('in door','in door'),
            ('out door','out door'),)
    name=models.CharField(max_length=200)
    price=models.FloatField(null=True)
    category=models.CharField(max_length=200,null=True ,choices=CATEGORY)
    description=models.CharField(max_length=500)
    date_created=models.DateTimeField(auto_now_add=True,null=True)
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return self.name

class Order(models.Model):
    STATUS=(('pending','pending'),
    ('out of delivery','out of delivery'),
    ('delivered','delivered'),)
    customer = models.ForeignKey(Customer,null=True,on_delete=models.SET_NULL)
    product = models.ForeignKey(Product,null=True,on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True,null=True)
    status = models.CharField(max_length=200, choices=STATUS)
    note=models.CharField(max_length=1200,null=True)
    def __str__(self):
        return self.product.name

accounts/forms.py
from django.forms import ModelForm

from accounts.models import Product, Order, Tag, Customer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CustomerForm(ModelForm):
    class Meta:
        model=Customer
        fields='__all__'
        exclude=['user']

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from . import urls

from .decorators import unauthenticated_user,allowed_users,admin_only
from django.forms import inlineformset_factory ,formset_factory# multiple form within one form
from django.urls import NoReverseMatch, reverse
from .models import *
from .forms import OrderForm,CreateUserForm,CustomerForm
from .filters import *

# Create your views here.
@unauthenticated_user
def registerPage(request):
	form = CreateUserForm()
	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			user=form.save()

			username = form.cleaned_data.get('username')
			group=Group.objects.get(name='customer')
			user.groups.add(group)
			Customer.objects.create(
			user=user,
			)
			messages.success(request, 'Account was created for ' + username)

			return redirect('accounts:login')


	context = {'form':form}
	return render(request, 'accounts/register.html', context)

@unauthenticated_user
def loginPage(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password =request.POST.get('password')

		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			return redirect('accounts:home')
		else:
			messages.info(request, 'Username OR password is incorrect')

	context = {}
	return render(request, 'accounts/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('accounts:login')


@login_required(login_url='accounts:login')
# @allowed_users(allowed_roles=['admin'])
@admin_only
def home(request):
	orders = Order.objects.all()
	customers = Customer.objects.all()

	total_customers = customers.count()

	total_orders = orders.count()
	delivered = orders.filter(status='delivered').count()
	pending = orders.filter(status='pending').count()

	context = {'orders':orders, 'customers':customers,
	'total_orders':total_orders,'delivered':delivered,
	'pending':pending }

	return render(request, 'accounts/dashboard.html', context)

# @login_required(login_url='login')
@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['customer'])
def userPage(request):
	orders = request.user.customer.order_set.all()
	total_orders = orders.count()
	delivered = orders.filter(status='delivered').count()
	pending = orders.filter(status='pending').count()
	# f"total orders{total_orders} pending {pending} delivered {delivered} "
	context={'orders':orders,
	'total_orders':total_orders,'delivered':delivered,
	'pending':pending,}
	return render(request,'accounts/user.html',context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['customer'])

def accountSettings(request):
	customer=request.user.customer
	form=CustomerForm(instance=customer)
	if request.method=='POST':
		form=CustomerForm(request.POST,request.FILES,instance=customer)
		if form.is_valid():
			form.save()

	context={'form':form}
	return render(request,'accounts/account_settings.html',context)
# def home(request):
#     orders=Order.objects.all()
#     customers=Customer.objects.all()
#     total_customer=customers.count()
#     total_orders= orders.count()
#     delivered=orders.filter(status='delivered').count()
#     pending=orders.filter(status='pending').count()
#     context={
#     'orders':orders,
#     'customers':customers,
#     'total_orders':total_orders,
#     'total_customer':total_customer,
#     'pending':pending,
#     'delivered':delivered,
#     }
#     return render(request,'accounts/dashboard.html',context)
@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def products(request):
    products=Product.objects.all()
    context={
    'products':products,
    }
    return render(request,'accounts/products.html',context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def customer(request, pk_test):
    customer=Customer.objects.get(id=pk_test)
    orders=customer.order_set.all()
    order_count=orders.count()
    myFilter=OrderFilter(request.GET,queryset=orders)
    orders =myFilter.qs
    context={'customer': customer,
    'orders':orders,
    'myFilter':myFilter}

    return render(request,'accounts/customer.html',context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def createOrder(request,pk):
    OrderFormSet=inlineformset_factory(Customer,Order, fields=('product','status'))
        #parent child
    customer=Customer.objects.get(id=pk)
    formset=OrderFormSet(queryset=Order.objects.none(),instance=customer)
    # form=OrderForm(initial={'customer':customer})

    if request.method == "POST":
        # print("request :",request.POST)
        form=OrderForm(request.POST)
        formset=OrderFormSet(request.POST,instance=customer)
        if formset.is_valid():
            formset.save()
            return redirect('/')
    context={'form':formset}
    return render(request,'accounts/order_form.html',context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])

def updateOrder(request,pk):
    # OrderFormSet=formset_factory(Order)
    #     #parent child
    # customer=Customer.objects.get(id=pk)
    order=Order.objects.get(id=pk)
    # OrderFormSet=inlineformset_factory(Customer,Order, fields=('product','status'))
    form=OrderForm(instance=order)
    # formset=OrderFormSet(initial=[{'customer':customer,}])

    if request.method == "POST":
        form=OrderForm(request.POST,instance=order)
        if form.is_valid():
            form.save()
            return redirect('/')

    context={'form':form}
    return render(request,'accounts/order_form.html',context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['admin'])
def deleteOrder(request,pk):
    order=Order.objects.get(id=pk)
    if request.method== "POST":
        order.delete()
        return redirect('/')

    context={'item':order}
    return render(request,'accounts/delete.html',context)

accounts/templates/accounts/account_settings.html
{%  extends 'accounts/main.html' %}
{% load static %}
{% block body %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'accounts:home' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.customer.profile_pic.url}}" >

		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">

			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
          {{ form.management_form }}
				{{form.as_p}}

			<input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
	</div>
</div>



{% endblock %}

accounts/templates/accounts/customer.html
  {% extends 'accounts/main.html' %}
  {% block body %}
<br>

	<div class="row">

		<div class="col-md">
			<div class="card card-body customer-card">
				<h5>Customer: {{customer.name}}</h5>
				<hr>
				<a href="" class="btn btn-outline-info btn-sm btn-block">Update Customer</a>
				<a href="{% url 'accounts:create_order' customer.id %}" class="btn btn-outline-info btn-sm btn-block">Place order</a>
			</div>
		</div>

		<div class="col-md">
			<div class="card card-body info-card">
				<h5>Contact Information</h5>
				<hr>
				<p>Email {{customer.email}} </p>
				<p>Phone: {{customer.phone}} </p>
			</div>
		</div>

		<div class="col-md">
			<div class="card card-body total-orders">
				<h5>Total Orders</h5>
				<hr>
				<h1 style="text-align: center; padding: 10px">{{orders.count}}</h1>
			</div>
		</div>

	</div>

<br>
	<div class="row">
		<div class="col">
			<div class="card card-body">
				<form method="get">
          {{myFilter.form}}
					<!-- {{myFilter.form}} -->
					<button class="btn btn-primary" type="submit">Search</button>
				</form>
			</div>
		</div>
	</div>
	<br>

	<div class="row">
		<div class="col-md">
			<div class="card card-body">
				<table class="table table-sm">
					<tr>
						<th>Product</th>
						<th>Note</th>
						<th>Date Ordered</th>
						<th>Status</th>
						<th>Update</th>
						<th>Remove</th>
					</tr>

					{% for o in orders %}
						<tr>
							<td>{{o.product}}</td>
							<td>{{o.note}}</td>
							<td>{{o.date_created}}</td>
							<td>{{o.status}}</td>
							<td><a href="{% url 'accounts:update_order' o.id %}" class="btn btn-warning btn-sm">Update</a></td>
							<td><a href="{% url 'accounts:delete_order' o.id %}" class="btn btn-danger btn-sm">Remove</a></td>
						</tr>
					{% endfor %}

				</table>
			</div>
		</div>
	</div>


{% endblock %}
  <!-- {% block content %}

  	<br>

  	<div class="row">

  		<div class="col-md">
  			<div class="card card-body customer-card">
  				<h5>Customer: {{customer.name}}</h5>
  				<hr>
  				<a href="" class="btn btn-outline-info btn-sm btn-block">Update Customer</a>
  				<a href="{% url 'create_order' customer.id %}" class="btn btn-outline-info btn-sm btn-block">Place order</a>
  			</div>
  		</div>

  		<div class="col-md">
  			<div class="card card-body info-card">
  				<h5>Contact Information</h5>
  				<hr>
  				<p>Email {{customer.email}} </p>
  				<p>Phone: {{customer.phone}} </p>
  			</div>
  		</div>

  		<div class="col-md">
  			<div class="card card-body total-orders">
  				<h5>Total Orders</h5>
  				<hr>
  				<h1 style="text-align: center; padding: 10px">{{orders.count}}</h1>
  			</div>
  		</div>

  	</div>

  <br>
  	<div class="row">
  		<div class="col">
  			<div class="card card-body">
  				<form method="get">
  					{{myFilter.form}}
  					<button class="btn btn-primary" type="submit">Search</button>
  				</form>
  			</div>
  		</div>
  	</div>
  	<br>

  	<div class="row">
  		<div class="col-md">
  			<div class="card card-body">
  				<table class="table table-sm">
  					<tr>
  						<th>Product</th>
  						<th>Category</th>
  						<th>Date Ordered</th>
  						<th>Status</th>
  						<th>Update</th>
  						<th>Remove</th>
  					</tr>

  					{% for o in orders %}
  						<tr>
  							<td>{{o.product}}</td>
  							<td>{{o.product.category}}</td>
  							<td>{{o.date_created}}</td>
  							<td>{{o.status}}</td>
  							<td><a href="" class="btn btn-warning btn-sm">Update</a></td>
  							<td><a href="" class="btn btn-danger btn-sm">Remove</a></td>
  						</tr>
  					{% endfor %}

  				</table>
  			</div>
  		</div>
  	</div>

  {% endblock %} -->

accounts/templates/accounts/dashboard.html
{% extends 'accounts/main.html' %}

{% block title %} Home {% endblock %}

{% block body %}

{% include 'accounts/status.html' %}
<br>
<div class="container-fluid row">
<!-- <h5>customer</h5> -->
<hr>
<div class="col-md-5">
  <a class="btn btn-primary"> create Customer </a>
  <table class="table">
    <tr>
      <th> Details</th>
      <th> Customer</th>
      <th> Phone</th>

    </tr>
{% for customer in customers %}
<tr>
  <td> <a class="btn btn-sm btn-info" href="{% url 'accounts:customer' customer.id %}">view</a></td>
  <td> {{customer.name}}</td>
  <td> {{customer.phone}}</td>
  <td> {{customer.price}}</td>
</tr>
{% endfor %}
</table>

  </div>

  <div class="col-md-7">
        <table class="table">
      <tr>
        <th> Product</th>
        <th> Date Ordered</th>
        <th> Status</th>
        <th> Update</th>
        <th> Remove</th>

      </tr>
  {% for i in orders %}
  <tr>
    <td> {{i.product}}</td>
    <td> {{i.date_created}}</td>
    <td> {{i.status}}</td>
      <td> <a class="btn btn-warning" href="{% url 'accounts:update_order' i.id %}">Update </a></td>
      <td> <a class="btn btn-danger" href="{% url 'accounts:delete_order' i.id %}"> Delete </a></td>
  </tr>
  {% endfor %}
  </table>

    </div>
</div>
<h2> This is the latest Home</h2>
<h1> Home </h1>

<p> this is our latest news contact me </p>
{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'accounts/main.html' %}

{% block title %} Delete {% endblock %}

{% block body %}
<h4 class="text-danger"> you really want to delete {{item}} ?? </h4>
<form  action="{% url 'accounts:delete_order' item.id %}" method="POST">
    {% csrf_token %}

    <a class="" href="{% url 'accounts:home' %}" > cancel</a>
    <input type="submit"  class="text-danger" name="Delete">
  </form>
{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

accounts/templates/accounts/main.html
<!DOCTYPE html>

{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css", href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "accounts/css/style.css" %}">
    {% include 'accounts/navbar.html' %}
  </head>
  <body>

{% block body %}

 {% endblock %}



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static '/accounts/js/script.js' %}">

</script>
  </body>


</html>

accounts/templates/accounts/navbar.html
{% load static %}
<style>
  .hello-msg{
    font-size:15px;
    color:#90fc03;
    margin-right:20px;
  }
  </style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <img src="{% static "/accounts/images/image.png" %}">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      {% if request.user.is_staff %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:home' %}">Dashboard  </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:products' %}">Producs</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:account' %}">Settings</a>
      </li>
      {% endif %}
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>

<span class="hello-msg"> Hello,{{request.user}} </span>
<span class="hello-msg"> <a href="{% url 'accounts:logout'%}" >Logout</a> </span>
</nav>

accounts/templates/accounts/order_form.html
{% extends 'accounts/main.html' %}

{% block title %} Order {% endblock %}

{% block body %}
<div class="container">
    <div class='row'>
          <form action="" method="POST">
            {% csrf_token %}
            {{ form.management_form }}
            {% for field in form %}
            {{ field }}
            <hr>
            {% endfor %}
          <input type='submit' name="submit" class='btn btn-md btn-success'>
            </form>
            </div>
          </div>



{% endblock %}

accounts/templates/accounts/products.html
{% extends 'accounts/main.html' %}

{% block title %} Home {% endblock %}

{% block body %}
<div class="row">
  <table class="table">
    <tr>
      <th> Product</th>
      <th> Category</th>
      <th> Price</th>
    </tr>
{% for i in products %}
<tr>
  <td> {{i.name}}</td>
  <td> {{i.category}}</td>
  <td> {{i.price}}</td>
</tr>
{% endfor %}
</table>
</div>
{% endblock %}

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>

					</form>
				</div>

				{{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>